[package]
name = "rustarch"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
codegen-units = 1 # Бустит скорость больше, чем на 0.5с!!
#lto = true
#debug = true

[profile.samply]
inherits = "release"
debug = true

[dependencies]
owo-colors = "4"
thiserror = "2"

[target.'cfg(windows)'.dependencies]
enable-ansi-support = "0"
